version: "3"

services:
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    # command: apt-get update; apt-get install -y net-tools iproute2 iputils-ping
    ports:
      - ${MONGODB_PORT:-27017}:${MONGODB_PORT:-27017}
    volumes:
      - ${MONGODB_PATH:-./mongodb}:/data/db
    networks:
      botnet:
        ipv4_address: 172.100.0.5
    # TODO: add auth

  chatgpt_telegram_bot:
    tty: true
    container_name: chatgpt_telegram_bot
    volumes:
      - ../chatgpt_telegram_bot:/code/
    restart: always
    # ports:
      # - "27017:27017"
    build:
      context: "."
      dockerfile: Dockerfile
    depends_on:
      - mongo

    command: python3 bot/bot.py

    networks:
      botnet:
        ipv4_address: 172.100.0.2

networks:
  botnet:
    ipam:
      config:
        - subnet: 172.100.0.0/16

  # mongo_express:
  #   container_name: mongo-express
  #   image: mongo-express:latest
  #   restart: always
  #   ports:
  #     - ${MONGO_EXPRESS_PORT:-8081}:${MONGO_EXPRESS_PORT:-8081}
  #   environment:
  #     - ME_CONFIG_MONGODB_SERVER=mongo
  #     - ME_CONFIG_MONGODB_PORT=${MONGODB_PORT:-27017}
  #     - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
  #     - ME_CONFIG_MONGODB_AUTH_DATABASE=chatgpt_telegram_bot
  #     - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_EXPRESS_USERNAME:-username}
  #     - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_EXPRESS_PASSWORD:-password}
  #   depends_on:
  #     - mongo
